[package]
name = "turborepo-json-rewrite"
version = "0.1.0"
edition = { workspace = true }
license = "MIT"

[dependencies]
jsonc-parser = "0.21.0"
thiserror = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }

[lints]
workspace = true
